packages:
  - services/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.1
  '@nestjs/common': ^11.1.9
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.1.9
  '@nestjs/cqrs': ^11.0.2
  '@nestjs/jwt': ^11.0.1
  '@nestjs/passport': ^11.0.5
  '@nestjs/platform-express': ^11.1.9
  '@nestjs/schedule': ^6.0.1
  '@nestjs/schematics': ^11.0.9
  '@nestjs/testing': ^11.1.9
  '@nestjs/typeorm': github:nestjs/typeorm
  '@scalar/nestjs-api-reference': ^1.0.8
  '@types/express': ^5.0.5
  '@types/jest': ^30.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^24.10.1
  '@types/passport-jwt': ^4.0.1
  '@types/uuid': ^11.0.0
  '@typescript-eslint/eslint-plugin': ^8.48.0
  '@typescript-eslint/parser': ^8.48.0
  argon2: ^0.44.0
  axios: ^1.13.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.3
  eslint: ^9.39.1
  globals: ^15.15.0
  ioredis: ^5.8.2
  jest: ^30.2.0
  jsonwebtoken: ^9.0.2
  jwks-rsa: ^3.2.0
  kafkajs: ^2.2.4
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  pg: ^8.16.3
  prettier: ^3.6.2
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  ts-jest: ^29.4.5
  ts-node: ^10.9.2
  ts-node-dev: ^2.0.0
  typeorm: ^0.3.27
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  uuid: ^13.0.0
  winston: ^3.18.3
  zod: ^4.1.13
