packages:
  - 'services/*'
  - 'packages/*'

catalog:
  # NestJS Core
  '@nestjs/common': ^11.1.9
  '@nestjs/core': ^11.1.9
  '@nestjs/config': ^4.0.2
  '@nestjs/typeorm': github:nestjs/typeorm
  '@nestjs/platform-express': ^11.1.9
  '@nestjs/passport': ^11.0.5
  '@nestjs/jwt': ^11.0.1
  '@nestjs/cqrs': ^11.0.2
  '@nestjs/schedule': ^6.0.1

  # Database
  typeorm: ^0.3.27
  pg: ^8.16.3

  # Auth
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  jwks-rsa: ^3.2.0
  jsonwebtoken: ^9.0.2
  argon2: ^0.44.0

  # Messaging & HTTP
  kafkajs: ^2.2.4
  axios: ^1.13.2

  # Utilities
  winston: ^3.18.3
  zod: ^4.1.13
  rxjs: ^7.8.2
  reflect-metadata: ^0.2.2
  class-validator: ^0.14.3
  class-transformer: ^0.5.1
  uuid: ^13.0.0
  ioredis: ^5.8.2
  '@scalar/nestjs-api-reference': ^1.0.8

  # Dev Dependencies
  typescript: ^5.9.3
  '@types/node': ^24.10.1
  ts-node-dev: ^2.0.0
  ts-node: ^10.9.2
  '@types/jsonwebtoken': ^9.0.10
  '@types/passport-jwt': ^4.0.1
  '@types/uuid': ^11.0.0
  '@types/express': ^5.0.5
  '@nestjs/testing': ^11.1.9
  '@nestjs/schematics': ^11.0.9
  '@types/jest': ^30.0.0
  '@typescript-eslint/eslint-plugin': ^8.48.0
  '@typescript-eslint/parser': ^8.48.0
  eslint: ^9.39.1
  jest: ^30.2.0
  prettier: ^3.6.2
  ts-jest: ^29.4.5
